### Head ###
head:
  icons:
    others:
      -
        image: assets/icons/favicon-16x16.png
        sizes: 16x16
      -
        image: assets/icons/favicon-32x32.png
        sizes: 32x32
      -
        image: assets/icons/favicon-48x48.png
        sizes: 48x48
      -
        image: assets/icons/favicon-64x64.png
        sizes: 64x64
      -
        image: assets/icons/favicon-96x96.png
        sizes: 96x96

    android:
      -
        image: assets/icons/android-icon-128x128.png
        sizes: 128x128
      -
        image: assets/icons/android-icon-192x192.png
        sizes: 192x192

    apple:
      -
        image: assets/icons/apple-icon-57x57.png
        sizes: 57x57
      -
        image: assets/icons/apple-icon-60x60.png
        sizes: 60x60
      -
        image: assets/icons/apple-icon-72x72.png
        sizes: 72x72
      -
        image: assets/icons/apple-icon-76x76.png
        sizes: 76x76
      -
        image: assets/icons/apple-icon-114x114.png
        sizes: 114x114
      -
        image: assets/icons/apple-icon-120x120.png
        sizes: 120x120
      -
        image: assets/icons/apple-icon-144x144.png
        sizes: 144x144
      -
        image: assets/icons/apple-icon-152x152.png
        sizes: 152x152
      -
        image: assets/icons/apple-icon-180x180.png
        sizes: 180x180

### Footer ###
# show_license: true
# show_social_links: true

footer:
  email: roliveira.moraes@gmail.com
  rss_path: feed.xml
  github_username:  rafaelmoraes
  twitter_username: rafaelmoraesdev
  linkedin_username: rafael-moraes-95986659

#RSS settings
rss: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: minima

### SEO ###
# google_analytics: UA-119153666-1 # rafaelmoraes.tech
google_analytics: UA-120007953-1 # rafaelmoraes.github.io

title: Rafael Moraes
url: "https://rafaelmoraes.github.io"
permalink: /:title
author: Rafael Moraes

twitter:
  username: rafaelmoraesdev

baseurl: "" #Dependência do github pages
description: "" #Dependência do github pages

timezone: America/Sao_Paulo

defaults:
  -
    scope:
      path: ''
    values:
      image: /assets/logo.png
  -
    scope:
      path: '_posts/en'
    values:
      layout:  'post'
      lang: 'en'
  -
    scope:
      path: '_posts/pt_BR'
    values:
      layout: 'post'
      lang: 'pt_BR'

disqus:
  # shortname: rafaelmoraes-pro
